package com.taotao.domain.model;

import java.io.Serializable;
import java.util.Date;

public class TbBigtype implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bigtype.id
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bigtype.bigName
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    private String bigName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bigtype.createTime
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_bigtype
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     * @param id 
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    public String getBigName() {
        return bigName;
    }

    /**
     *
     * @param bigName 
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    public void setBigName(String bigName) {
        this.bigName = bigName;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *
     * @param createTime 
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}