package com.taotao.domain.model;

import java.io.Serializable;
import java.util.Date;

public class TbGoods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.id
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.bigId
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    private Integer bigId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.smallId
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    private Integer smallId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goodsName
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goodsFrom
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    private String goodsFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.createTime
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.nowPrice
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    private Float nowPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.freePrice
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    private Float freePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.number
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.pirture
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    private String pirture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.mark
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    private Integer mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.introduce
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_goods
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     * @param id 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public Integer getBigId() {
        return bigId;
    }

    /**
     *
     * @param bigId 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public void setBigId(Integer bigId) {
        this.bigId = bigId;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public Integer getSmallId() {
        return smallId;
    }

    /**
     *
     * @param smallId 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public void setSmallId(Integer smallId) {
        this.smallId = smallId;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     *
     * @param goodsName 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public String getGoodsFrom() {
        return goodsFrom;
    }

    /**
     *
     * @param goodsFrom 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public void setGoodsFrom(String goodsFrom) {
        this.goodsFrom = goodsFrom;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *
     * @param createTime 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public Float getNowPrice() {
        return nowPrice;
    }

    /**
     *
     * @param nowPrice 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public void setNowPrice(Float nowPrice) {
        this.nowPrice = nowPrice;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public Float getFreePrice() {
        return freePrice;
    }

    /**
     *
     * @param freePrice 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public void setFreePrice(Float freePrice) {
        this.freePrice = freePrice;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public Integer getNumber() {
        return number;
    }

    /**
     *
     * @param number 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public String getPirture() {
        return pirture;
    }

    /**
     *
     * @param pirture 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public void setPirture(String pirture) {
        this.pirture = pirture;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public Integer getMark() {
        return mark;
    }

    /**
     *
     * @param mark 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     *
     * @param introduce 
     *
     * @mbggenerated Fri Dec 16 15:03:09 CST 2016
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }
}