package com.taotao.domain.model;

import java.io.Serializable;

public class TbLink implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_link.id
     *
     * @mbggenerated Fri Dec 16 15:03:36 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_link.linkName
     *
     * @mbggenerated Fri Dec 16 15:03:36 CST 2016
     */
    private String linkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_link.linkAddress
     *
     * @mbggenerated Fri Dec 16 15:03:36 CST 2016
     */
    private String linkAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_link
     *
     * @mbggenerated Fri Dec 16 15:03:36 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:36 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     * @param id 
     *
     * @mbggenerated Fri Dec 16 15:03:36 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:36 CST 2016
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     *
     * @param linkName 
     *
     * @mbggenerated Fri Dec 16 15:03:36 CST 2016
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:03:36 CST 2016
     */
    public String getLinkAddress() {
        return linkAddress;
    }

    /**
     *
     * @param linkAddress 
     *
     * @mbggenerated Fri Dec 16 15:03:36 CST 2016
     */
    public void setLinkAddress(String linkAddress) {
        this.linkAddress = linkAddress;
    }
}