package com.taotao.domain.model;

import java.io.Serializable;

public class TbManager implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.id
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.account
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.password
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.name
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.sign
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    private Integer sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_manager
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     * @param id 
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     *
     * @param account 
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     *
     * @param password 
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     *
     * @param name 
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    public Integer getSign() {
        return sign;
    }

    /**
     *
     * @param sign 
     *
     * @mbggenerated Fri Dec 16 15:04:07 CST 2016
     */
    public void setSign(Integer sign) {
        this.sign = sign;
    }
}