package com.taotao.domain.model;

import java.io.Serializable;

public class TbMember implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.id
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.name
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.password
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.reallyName
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    private String reallyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.age
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.profession
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    private String profession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.email
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.question
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_member.result
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_member
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     * @param id 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     *
     * @param name 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     *
     * @param password 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public String getReallyName() {
        return reallyName;
    }

    /**
     *
     * @param reallyName 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public void setReallyName(String reallyName) {
        this.reallyName = reallyName;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     *
     * @param age 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public String getProfession() {
        return profession;
    }

    /**
     *
     * @param profession 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public void setProfession(String profession) {
        this.profession = profession;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     *
     * @param email 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public String getQuestion() {
        return question;
    }

    /**
     *
     * @param question 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public String getResult() {
        return result;
    }

    /**
     *
     * @param result 
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    public void setResult(String result) {
        this.result = result;
    }
}