package com.taotao.domain.model;

import java.io.Serializable;

public class TbOrderdetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderdetail.id
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderdetail.orderNumber
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderdetail.goodsId
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderdetail.price
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderdetail.number
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_orderdetail
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     * @param id 
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     *
     * @param orderNumber 
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     *
     * @param goodsId 
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    public Float getPrice() {
        return price;
    }

    /**
     *
     * @param price 
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    public Integer getNumber() {
        return number;
    }

    /**
     *
     * @param number 
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}