package com.taotao.domain.model;

import java.io.Serializable;
import java.util.Date;

public class TbOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.id
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.number
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.name
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.reallyName
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    private String reallyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.address
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.tel
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.setMoney
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    private String setMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.post
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.sign
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    private Integer sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.createTime
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.bz
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     * @param id 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public String getNumber() {
        return number;
    }

    /**
     *
     * @param number 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     *
     * @param name 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public String getReallyName() {
        return reallyName;
    }

    /**
     *
     * @param reallyName 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public void setReallyName(String reallyName) {
        this.reallyName = reallyName;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     *
     * @param address 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     *
     * @param tel 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public String getSetMoney() {
        return setMoney;
    }

    /**
     *
     * @param setMoney 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public void setSetMoney(String setMoney) {
        this.setMoney = setMoney;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public String getPost() {
        return post;
    }

    /**
     *
     * @param post 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public void setPost(String post) {
        this.post = post;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public Integer getSign() {
        return sign;
    }

    /**
     *
     * @param sign 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public void setSign(Integer sign) {
        this.sign = sign;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *
     * @param createTime 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *
     * @return 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public String getBz() {
        return bz;
    }

    /**
     *
     * @param bz 
     *
     * @mbggenerated Fri Dec 16 15:04:51 CST 2016
     */
    public void setBz(String bz) {
        this.bz = bz;
    }
}