package com.taotao.domain.dao;

import com.taotao.domain.model.TbAffiche;
import com.taotao.domain.model.TbAfficheExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbAfficheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    int countByExample(TbAfficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    int deleteByExample(TbAfficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    int insert(TbAffiche record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    int insertSelective(TbAffiche record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    int insertBatch(@Param("list") List<TbAffiche> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    List<TbAffiche> selectByExampleWithBLOBs(TbAfficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    List<TbAffiche> selectByExample(TbAfficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    TbAffiche selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    int updateByExampleSelective(@Param("record") TbAffiche record, @Param("example") TbAfficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") TbAffiche record, @Param("example") TbAfficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    int updateByExample(@Param("record") TbAffiche record, @Param("example") TbAfficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    int updateByPrimaryKeySelective(TbAffiche record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TbAffiche record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_affiche
     *
     * @mbggenerated Fri Dec 16 14:59:47 CST 2016
     */
    int updateByPrimaryKey(TbAffiche record);
}