package com.taotao.domain.dao;

import com.taotao.domain.model.TbBigtype;
import com.taotao.domain.model.TbBigtypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbBigtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bigtype
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    int countByExample(TbBigtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bigtype
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    int deleteByExample(TbBigtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bigtype
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bigtype
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    int insert(TbBigtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bigtype
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    int insertSelective(TbBigtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bigtype
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    int insertBatch(@Param("list") List<TbBigtype> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bigtype
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    List<TbBigtype> selectByExample(TbBigtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bigtype
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    TbBigtype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bigtype
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") TbBigtype record, @Param("example") TbBigtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bigtype
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    int updateByExample(@Param("record") TbBigtype record, @Param("example") TbBigtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bigtype
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    int updateByPrimaryKeySelective(TbBigtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bigtype
     *
     * @mbggenerated Fri Dec 16 15:02:42 CST 2016
     */
    int updateByPrimaryKey(TbBigtype record);
}