package com.taotao.domain.dao;

import com.taotao.domain.model.TbMember;
import com.taotao.domain.model.TbMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    int countByExample(TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    int deleteByExample(TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    int insert(TbMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    int insertSelective(TbMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    int insertBatch(@Param("list") List<TbMember> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    List<TbMember> selectByExample(TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    TbMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    int updateByExampleSelective(@Param("record") TbMember record, @Param("example") TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    int updateByExample(@Param("record") TbMember record, @Param("example") TbMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    int updateByPrimaryKeySelective(TbMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_member
     *
     * @mbggenerated Fri Dec 16 15:04:30 CST 2016
     */
    int updateByPrimaryKey(TbMember record);
}