package com.taotao.domain.dao;

import com.taotao.domain.model.TbOrderdetail;
import com.taotao.domain.model.TbOrderdetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbOrderdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    int countByExample(TbOrderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    int deleteByExample(TbOrderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    int insert(TbOrderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    int insertSelective(TbOrderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    int insertBatch(@Param("list") List<TbOrderdetail> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    List<TbOrderdetail> selectByExample(TbOrderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    TbOrderdetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    int updateByExampleSelective(@Param("record") TbOrderdetail record, @Param("example") TbOrderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    int updateByExample(@Param("record") TbOrderdetail record, @Param("example") TbOrderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    int updateByPrimaryKeySelective(TbOrderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated Fri Dec 16 15:05:15 CST 2016
     */
    int updateByPrimaryKey(TbOrderdetail record);
}