package com.taotao.domain.dao;

import com.taotao.domain.model.TbSmalltype;
import com.taotao.domain.model.TbSmalltypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbSmalltypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_smalltype
     *
     * @mbggenerated Fri Dec 16 15:05:36 CST 2016
     */
    int countByExample(TbSmalltypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_smalltype
     *
     * @mbggenerated Fri Dec 16 15:05:36 CST 2016
     */
    int deleteByExample(TbSmalltypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_smalltype
     *
     * @mbggenerated Fri Dec 16 15:05:36 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_smalltype
     *
     * @mbggenerated Fri Dec 16 15:05:36 CST 2016
     */
    int insert(TbSmalltype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_smalltype
     *
     * @mbggenerated Fri Dec 16 15:05:36 CST 2016
     */
    int insertSelective(TbSmalltype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_smalltype
     *
     * @mbggenerated Fri Dec 16 15:05:36 CST 2016
     */
    int insertBatch(@Param("list") List<TbSmalltype> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_smalltype
     *
     * @mbggenerated Fri Dec 16 15:05:36 CST 2016
     */
    List<TbSmalltype> selectByExample(TbSmalltypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_smalltype
     *
     * @mbggenerated Fri Dec 16 15:05:36 CST 2016
     */
    TbSmalltype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_smalltype
     *
     * @mbggenerated Fri Dec 16 15:05:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") TbSmalltype record, @Param("example") TbSmalltypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_smalltype
     *
     * @mbggenerated Fri Dec 16 15:05:36 CST 2016
     */
    int updateByExample(@Param("record") TbSmalltype record, @Param("example") TbSmalltypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_smalltype
     *
     * @mbggenerated Fri Dec 16 15:05:36 CST 2016
     */
    int updateByPrimaryKeySelective(TbSmalltype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_smalltype
     *
     * @mbggenerated Fri Dec 16 15:05:36 CST 2016
     */
    int updateByPrimaryKey(TbSmalltype record);
}